export enum SERIALIZE_GROUP {
  GROUP_BASE = 'GROUP_BASE',
  GROUP_ALL_USER = 'GROUP_ALL_USERS',
  GROUP_USER = 'GROUP_USER',
  GROUP_ALL_ORDER = 'GROUP_ALL_ORDER',
  GROUP_ALL_PRODUCT = 'GROUP_ALL_PRODUCT',
  GROUP_ALL_ORDER_ITEM = 'GROUP_ALL_ORDER_ITEM',
}
